url: "https://treehouse.co" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Treehouse" # the name of your site, e.g. ACME Corp.
logo: '/assets/img/logo.png'
logo_svg: '/assets/img/logo.svg'
icon: '/assets/img/01.png'

exclude:
  - config
  - plugins
  - Capfile
  - README.md

include:
  - _redirects

# Build settings
markdown: kramdown
permalink: /:categories/blog/:title:output_ext

# Sass
sass:
  sass_dir: _sass
  style: compressed

toc:
  min_level: 2
  max_level: 2

# collections_dir: collections
collections:
  posts:
    output: false
  products:
    output: false

# Author Settings
author:
  name: TreeHouse.co
  image: '/assets/img/logo.png'
  logo: '/assets/img/logo.png'
  job: TreeHouse
  bio: Passionate designer curating designs for new startups  and  founders  and crafts  beautiful user interfaces with love.
  email: hello@treehouse.co

plugins:
  - jekyll-sitemap
  - jekyll-toc
  - amp-jekyll
  - jekyll-seo-tag
  - jekyll-treehouse

ampdir: amp

seo:
  organization:
    name: Treehouse.co
    same_as:
    logo:
      url: 'https://treehouse.co/assets/img/logo.png'
      width: 512
      height: 512
  website:
    name: Treehouse.co
  person:
    name: Treehouse
    id: 'author/treehouse'

defaults:
  #languages
  -
    scope:
      path: ""
    values:
      lang: "en"
      full-lang: "en"
  # US
  -
    scope:
      path: "us"
    values:
      lang: "us"
      full-lang: 'en-US'
  -
    scope:
      path: "_posts/us"
    values:
      lang: "us"
      full-lang: 'en-US'
      categories: "us"
  # DE
  -
    scope:
      path: "de"
    values:
      lang: "de"
      full-lang: 'de-DE'
  -
    scope:
      path: "_posts/de"
    values:
      lang: "de"
      full-lang: 'de-DE'
      categories: "de"
  # FR
  -
    scope:
      path: "fr"
    values:
      lang: "fr"
      full-lang: 'fr-FR'
  -
    scope:
      path: "_posts/fr"
    values:
      lang: "fr"
      full-lang: 'fr-FR'
      categories: "fr"
  # ES
  -
    scope:
      path: "es"
    values:
      lang: "es"
      full-lang: 'es-ES'
  -
    scope:
      path: "_posts/es"
    values:
      lang: "es"
      full-lang: 'es-ES'
      categories: "es"
  # IT
  -
    scope:
      path: "it"
    values:
      lang: "it"
      full-lang: 'it-IT'
  -
    scope:
      path: "_posts/it"
    values:
      lang: "it"
      full-lang: 'it-IT'
      categories: "it"

  # PL
  -
    scope:
      path: "pl"
    values:
      lang: "pl"
      full-lang: "pl"
  -
    scope:
      path: "_posts/pl"
    values:
      lang: "pl"
      full-lang: "pl"
      categories: "pl"
  -
    scope:
      path: "_products/pl"
    values:
      lang: "pl"
      full-lang: "pl"
  -
    scope:
      path: "pl/recenzje"
    values:
      type: "ranking"

disqus-identifier: treehouse-co

i18n:
  pl:
    read_more: "Przeczytaj całość"
    published: "Opublikowano"
    updated: "Data aktualizacji"
    toc: "Spis treści"
    read_also: "Przeczytaj również"
    leave_comment: "Zostaw komentarz"
    title: 'Zainspiruj się i stwórz z nami swój wymarzony dom! - Treehouse'
    home_and_garden: Dom i Ogród
    select_country: "Wybierz kraj"
    home_page: "Strona główna"
    blog_page: "Artykuły"
    autor_label: "Autor"
    contact_label: "Kontakt"
    author_description: "Dorota jest z wykształcenia ekonomistką, ale jej największym hobby jest fotografia i aranżacja wnętrz. Z Treehouse współpracuje od początku 2019 roku."
    promoted_articles: "Promowane artykuły"
    next_article: "Następny artykuł"
    previous_article: "Poprzedni artykuł"
    maybe_interesting: "Może zainteresuje Cię"
    ranking: "Ranking"
    ranking_page_slug: "recenzje"
    ranking_page: "Recenzje"
    recent_articles: "Najnowsze Artykuły"
    recent_rankings: "Najnowsze Recenzje"    
    featured_rankings: "Polecane Recenzje"
    featured_articles: "Polecane Artykuły"
    boolean:
      true: Tak
      false: Nie
    properties:
      type: Rodzaj
      size: Rozmiar
      brand: Marka
      material: Materiał
      hardness: Twardość
      height: Wysokość
      inset: Wkład
      case: Pokrowiec
      bilateral: Dwustronny
      handles: Uchwyty do podnoszenia
      energy_class: Klasa energetyczna
      type_of_drum: Rodzaj bębna
      load: Maksymalny załadunek (kg)
      maximum_spin_speed: Maksymalna prędkość wirowania
      annual_energy_usage: Roczne zużycie energii
      annual_water_usage: Roczne zużycie wody
      height: Wysokość
      shape: Kształt
      coating: Powłoka
      lid: Pokrywka
      holder: Rączka
      color: Kolor
      functionality: Funkcjonalność
      pressure: Ciśnienie
      strength: Moc
      type_of_coffee: Rodzaj kawy
      milk_frothing_function: Funkcja spieniania mleka
      mumber_of_types_of_drinks: Ilość rodzajów napojów
      warranty: Gwarancja
      mill: Posiada młynek

  us:
    read_more: "Read more"
    published: "Published"
    updated: "Last update"
    toc: "Table of Content"
    read_also: "Read also"
    leave_comment: "Leave a comment"
    title: 'Get inspired and create your dream home with us! - Treehouse'
    home_and_garden: Home & Garden
    select_country: "Select country"
    home_page: "Home page"
    blog_page: "Articles"
    autor_label: "Author"
    contact_label: "Contact"
    author_description: "Dorota is an economist by profession, but her biggest hobby is photography and interior design. In Treehouse since the beginning of 2019."
    promoted_articles: "Featured articles"
    next_article: "Next article"
    previous_article: "Previous article"
    maybe_interesting: "Maybe you're interested"
    ranking: "Ranking"
    ranking_page_slug: "reviews"
    ranking_page: "Reviews"
    recent_articles: "Recent Articles"
    recent_rankings: "Recent Rankings"
    featured_rankings: "Featured Rankings"
    featured_articles: "Featured Articles"

  de:
    read_more: "Lesen Sie mehr"
    published: "Veröffentlicht"
    updated: "Letzte Aktualisierung"
    toc: "Inhaltsverzeichnis"
    read_also: "Lesen Sie auch"
    leave_comment: "Einen Kommentar hinterlassen"
    title: 'Lassen Sie sich inspirieren und schaffen Sie mit uns Ihr Traumhaus! - Treehouse'
    home_and_garden: Haus & Garten
    select_country: "Land auswählen"
    home_page: "Startseite"
    blog_page: "Artikel"
    autor_label: "Autor"
    contact_label: "Kontakt"
    author_description: "Dorota ist von Beruf Wirtschaftswissenschaftlerin, aber ihr größtes Hobby ist die Fotografie und Innenarchitektur. Seit Anfang 2019 in Treehouse."
    promoted_articles: "Empfohlene Artikel"
    next_article: "Nächster Artikel"
    previous_article: "Vorheriger Artikel"
    maybe_interesting: "Vielleicht sind Sie interessiert"
    ranking: "Rangliste"
    ranking_page_slug: "rezensionen"
    ranking_page: "Rezensionen"
    recent_articles: "Aktuelle Posts"
    recent_rankings: "Aktuelle Rankings"
    featured_rankings: "Ausgewählte Ranglisten"
    featured_articles: "Empfohlene Artikel"


  es:
    read_more: "Leer más..."
    published: "Publicado"
    updated: "Última actualización"
    toc: "Tabla de contenido"
    read_also: "Lea también"
    leave_comment: "Deje un comentario"
    title: 'Inspírese y cree la casa de sus sueños con nosotros! - Treehouse'
    home_and_garden: Hogar y Jardín
    select_country: "Seleccione el país"
    home_page: "Página de inicio"
    blog_page: "Artículos"
    autor_label: "Autor"
    contact_label: "Contacte con"
    author_description: "Dorota es economista de profesión, pero su mayor hobby es la fotografía y el diseño de interiores. En Treehouse desde principios de 2019."
    promoted_articles: "Artículos destacados"
    next_article: "Próximo artículo"
    previous_article: "Artículo anterior"
    maybe_interesting: "Tal vez te interese"
    ranking: "Clasificación"
    ranking_page_slug: "resenas"
    ranking_page: "Reseñas"
    recent_articles: "Mensajes recientes"
    recent_rankings: "Clasificaciones recientes"
    featured_rankings: "Rankings destacados"
    featured_articles: "Artículos destacados"


  fr:
    read_more: "En savoir plus"
    published: "Publié"
    updated: "Dernière mise à jour"
    toc: "Table des matières"
    read_also: "A lire également"
    leave_comment: "Laissez un commentaire"
    title: 'Laissez-vous inspirer et créez la maison de vos rêves avec nous ! - Treehouse'
    home_and_garden: Maison et jardin
    select_country: "Sélectionnez un pays"
    home_page: "Page d'accueil"
    blog_page: "Articles"
    autor_label: "Auteur"
    contact_label: "Contactez"
    author_description: "Dorota est économiste de profession, mais son plus grand hobby est la photographie et la décoration d'intérieur. Elle est à Treehouse depuis le début de l'année 2019."
    promoted_articles: "Articles de fond"
    next_article: "Article suivant"
    previous_article: "Article précédent"
    maybe_interesting: "Peut-être êtes-vous intéressé"
    ranking: "Classement"
    ranking_page_slug: "commentaires"
    ranking_page: "Commentaires"
    recent_articles: "Messages récents"
    recent_rankings: "Classements Récents"
    featured_rankings: "Classements en vedette"
    featured_articles: "Articles de fond"


  it:
    read_more: "Per saperne di più"
    published: "Pubblicato"
    updated: "Ultimo aggiornamento"
    toc: "Indice dei contenuti"
    read_also: "Leggi anche"
    leave_comment: "Lascia un commento"
    title: 'Lasciatevi ispirare e create la vostra casa dei sogni con noi! - Treehouse'
    home_and_garden: Casa e giardino
    select_country: "Seleziona il paese"
    home_page: "Pagina iniziale"
    blog_page: "Articoli"
    autor_label: "Autore"
    contact_label: "Contatto"
    author_description: "Dorota è un'economista di professione, ma il suo più grande hobby è la fotografia e il design d'interni. A Treehouse dall'inizio del 2019."
    promoted_articles: "Articoli in primo piano"
    next_article: "Prossimo articolo"
    previous_article: "Articolo precedente"
    maybe_interesting: "Forse siete interessati"
    ranking: "Classifica"
    ranking_page_slug: "recensioni"
    ranking_page: "Reviews"
    recent_articles: "Messaggi Recenti"
    recent_rankings: "Classifiche Recenti"
    featured_rankings: "Classifiche in primo piano"
    featured_articles: "Articoli in primo piano"


  en:
    read_more: "Read more"
    published: "Published"
    updated: "Last update"
    toc: "Table of Content"
    read_also: "Read also"
    leave_comment: "Leave a comment"
    title: 'Get inspired and create your dream home with us! - Treehouse'
    home_and_garden: Home & Garden
    select_country: "Select country"
    home_page: "Home page"
    blog_page: "Articles"
    autor_label: "Author"
    contact_label: "Contact"
    author_description: "Dorota is an economist by profession, but her biggest hobby is photography and interior design. In Treehouse since the beginning of 2019."
    promoted_articles: "Featured articles"
    next_article: "Next article"
    previous_article: "Maybe you're interested"
