url: "https://treehouse.co" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.
logo: '/assets/img/logo.png'
logo_svg: '/assets/img/logo.svg'
icon: '/assets/img/01.png'

# Build settings
markdown: kramdown
permalink: /:categories/blog/:title:output_ext

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude:
  - config
  - plugins
  - Capfile
  - README.md

# Author Settings
author:
  name: TreeHouse.co
  image: '/assets/img/logo.png'
  logo: '/assets/img/logo.png'
  job: TreeHouse
  bio: Passionate designer curating designs for new startups  and  founders  and crafts  beautiful user interfaces with love.
  email: hello@treehouse.co

plugins:
  - jekyll-sitemap
  - jekyll-toc
  - amp-jekyll
  - jekyll-seo-tag
  - jekyll-treehouse

ampdir: amp

seo:
  organization:
    name: Treehouse.co
    same_as:
    logo:
      url: 'https://treehouse.co/assets/img/logo.png'
      width: 106
      height: 100
  website:
    name: Treehouse.co
  person:
    name: Treehouse
    id: 'author/treehouse'
defaults:
  #languages
  -
    scope:
      path: ""
    values:
      lang: "en"
      full-lang: "en"
  -
    scope:
      path: "us"
    values:
      lang: "us"
      full-lang: 'en-US'
  -
    scope:
      path: "pl"
    values:
      lang: "pl"
      full-lang: "pl"

disqus-identifier: treehouse-co

i18n:
  pl:
    read_more: "Przeczytaj całość"
    published: "Opublikowano"
    toc: "Spis treści"
    read_also: "Przeczytaj również"
    leave_comment: "Zostaw komentarz"
    title: 'Zainspiruj się i stwórz z nami swój wymarzony dom! - Treehouse'
  us:
    read_more: "Read more"
    published: "Published"
    toc: "Table of Content"
    read_also: "Read also"
    leave_comment: "Leave a comment"
    title: 'Get inspired and create your dream home with us! - Treehouse'

  en:
    read_more: "Read more"
    published: "Published"
    toc: "Table of Content"
    read_also: "Read also"
    leave_comment: "Leave a comment"
    title: 'Get inspired and create your dream home with us! - Treehouse'
