title: TreeHouse - zainspiruj się
logo:  # you can add own logo.
description: Passionate designer curating designs for new startups  and  founders  and crafts  beautiful user interfaces with love.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
destination: ../_build

# Author Settings
author:
  name: TreeHouse
  image: '/assets/img/01.jpg'
  job: TreeHouse
  bio: Passionate designer curating designs for new startups  and  founders  and crafts  beautiful user interfaces with love.
  email: hello@treehouse.co

# Contact links
contact:
  - name: Twitter
    link: https://twitter.com/
  - name: Facebook
    link: https://facebook.com/
  - name: Instagram
    link: https://instagram.com/

social:
  name: TreeHouse
  links:
    - https://twitter.com/treehouse_co
    - https://www.facebook.com/treehouse_co
    - https://www.linkedin.com/in/treehouse_co
    - https://github.com/treehouse_co
    - https://keybase.io/treehouse_co

# Comment Section (Disqus)
disqus-identifier: treehouse_co # add your shortname for Disqus Comment. For example mr-brown

# Google Analytics
google-analytics: # add your identifier. For example UA-99631805-1.

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-toc
  - jekyll-seo-tag

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
