---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: _data
  label: _Data
  create: all
  match: "**/*"
  new_doc_ext: yml
- type: directory
  path: ''
  label: _International
  create: all
  match: "*"
- type: heading
  label: PL
- type: directory
  path: pl
  label: Strony
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: collections/_posts/pl
  label: Posty
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - blog-post
- type: directory
  path: pl/recenzje
  label: Rankingi
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - ranking
- type: directory
  path: collections/_products/pl
  label: Produkty
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - product-lamp
  - product-mattress
- type: heading
  label: US
- type: directory
  path: us
  label: Strony
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: collections/_posts/us
  label: Posty
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - blog-post
- type: directory
  path: us/recenzje
  label: Rankingi
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - ranking
- type: directory
  path: collections/_products/us
  label: Produkty
  create: all
  match: "**/*"
  new_doc_ext: md
- type: heading
  label: DE
- type: directory
  path: de
  label: Strony
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: collections/_posts/de
  label: Posty
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - blog-post
- type: directory
  path: de/recenzje
  label: Rankingi
  create: all
  match: "**/*"
  new_doc_ext: ".md"
  templates:
  - ranking
- type: heading
  label: ES
- type: directory
  path: es
  label: Strony
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: collections/_posts/es
  label: Posty
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - blog-post
- type: directory
  path: es/recenzje
  label: Rankingi
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - ranking
- type: heading
  label: FR
- type: directory
  path: fr
  label: Strony
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: collections/_posts/fr
  label: Posty
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - blog-post
- type: directory
  path: fr/recenzje
  label: Rankingi
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - ranking
- type: heading
  label: IT
- type: directory
  path: it
  label: Strony
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: collections/_posts/it
  label: Posty
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - blog-post
- type: directory
  path: it/recenzje
  label: Rankingi
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - ranking
- type: heading
  label: Jekyll
- type: document
  path: _config.yml
  label: Configuration
  read_only: true
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
