---
label: Product [Base]
hide_body: true
fields:
- name: name
  type: text
  config:
    required: true
  label: Nazwa
- name: description
  type: textarea
  default: ''
  config:
    required: true
    wysiwyg: true
    schema:
      format: markdown
  label: Opis
