---
label: Product [Patelnie]
hide_body: true
fields:
- name: category
  type: text
  config:
    required: false
  label: Kategoria
  hidden: true
  default: patelnie
- name: basics
  type: include
  config: {}
  template: product
  label: Basics
  description: Podstawowe informacje o produkcie
- name: properties
  type: field_group
  config: {}
  fields:
  - name: type
    type: text
    config:
      required: false
    label: Typ
  - name: material
    type: text
    config:
      required: false
    label: Materiał
  - name: brand
    type: text
    config:
      required: false
    label: Marka
  - name: size
    type: text
    config:
      required: false
    label: Rozmiar
  - name: shape
    type: text
    config:
      required: false
    label: Kształt
  - name: coating
    type: text
    config:
      required: false
    label: Powłoka
  - name: lid
    type: text
    config:
      required: false
    label: Pokrywka
  - name: holder
    type: text
    config:
      required: false
    label: Rączka
  - name: color
    type: text
    config:
      required: false
    label: Kolor
  label: Właściwości
  description: Właściwości produktu
