---
label: Product [Ekspresy do kawy]
hide_body: true
fields:
- name: category
  type: text
  config:
    required: false
  label: Kategoria
  hidden: true
  default: ekspresy-do-kawy
- name: basics
  type: include
  config: {}
  template: product
  label: Basics
  description: Podstawowe informacje o produkcie
- name: properties
  type: field_group
  config: {}
  fields:
  - name: type
    type: text
    config:
      required: false
    label: Typ
  - name: functionality
    type: text
    config:
      required: false
    label: Funkcjonalność
  - name: brand
    type: text
    config:
      required: false
    label: Marka
  - name: mill
    type: boolean
    label: Posiada młynek
  - name: pressure
    type: text
    config:
      required: false
    label: Ciśnienie
  - name: strength
    type: text
    config:
      required: false
    label: Moc
  - name: type_of_coffee
    type: text
    config:
      required: false
    label: Rodzaj kawy
  - name: milk_frothing_function
    type: boolean
    label: Funkcja spieniania mleka
  - name: mumber_of_types_of_drinks
    type: text
    config:
      required: false
    label: Ilość rodzajów napojów
  - name: warranty
    type: text
    config:
      required: false
    label: Gwarancja
  label: Właściwości
  description: Właściwości produktu
pages:
- _products/pl/ekspres-philips-daily-collection-hd7459-20.md
- _products/pl/ekspresy/ekspres-bosch-tassimo-suny-tas-3205-t32-niebieski.md
- _products/pl/ekspresy/ekspres-delonghi-bco-411b.md
- _products/pl/ekspresy/ekspres-delonghi-dolce-gusto-edg737b.md
- _products/pl/ekspresy/ekspres-delonghi-ecam-35055b.md
- _products/pl/ekspresy/ekspres-delonghi-eci-341w.md
- _products/pl/ekspresy/ekspres-delonghi-icm-152101.md
- _products/pl/ekspresy/ekspres-delonghi-magnifica-s-ecam-22110b.md
- _products/pl/ekspresy/ekspres-delonghi-scultura-ecz-351w-bialy.md
- _products/pl/ekspresy/ekspres-krups-kp123b31-nescafe-dolce-gusto-mini-szary.md
- _products/pl/ekspresy/ekspres-krups-nespresso-inissia-xn1001.md
- _products/pl/ekspresy/ekspres-krups-xp320830-opio.md
- _products/pl/ekspresy/ekspres-nescafe-dolce-gusto-krups-infinisima-kp1701-bialy.md
- _products/pl/ekspresy/ekspres-nescafe-dolce-gusto-krups-piccolo-kp100b-antracytowy.md
- _products/pl/ekspresy/ekspres-philips-2200-lattego-ep2230-10-czarny.md
- _products/pl/ekspresy/ekspres-philips-3000-easy-cappuccino-hd8829-09-czarny.md
- _products/pl/ekspresy/ekspres-philips-3200-lattego-premium-ep3241-50-czarny.md
- _products/pl/ekspresy/ekspres-philips-cafe-gaia-hd7546-20-metal.md
- _products/pl/ekspresy/ekspres-richards-morphy-prism-163001.md
- _products/pl/ekspresy/ekspres-saeco-picobaristo-sm5460-10-czarny.md
- _products/pl/ekspresy/ekspres-sage-barista-express-ses875bks.md
- _products/pl/ekspresy/ekspres-smeg-ecf01creu.md
