---
label: Product [Materace]
hide_body: true
fields:
- name: basics
  type: include
  config: {}
  template: product
  label: Basics
  description: Podstawowe dane o produkcie
- name: properties
  type: field_group
  config: {}
  fields:
  - name: type
    type: text
    config:
      required: true
    label: Typ
    description: Typ materaca
  - name: product_size
    type: text
    config:
      required: true
    label: Rozmiar
  - name: brand
    type: text
    config:
      required: true
    label: Marka
  - name: hardness
    type: text
    config:
      required: true
    label: Twardość
  - name: height
    type: text
    config:
      required: true
    label: Wysokość
  - name: inset
    type: text
    config:
      required: true
    label: Wkład
  - name: case
    type: text
    config:
      required: true
    label: Pokrowiec
  - name: bilateral
    type: boolean
    label: Dwustronny
  - name: handles
    type: boolean
    label: Uchwyty
  label: Właściwości
  description: Użyj ", " aby dodać kilka wartości dla jednej właściwości
pages:
- _products/pl/materace/baby-comfort-materasso-piankowy-60-120.md
- _products/pl/materace/breakdance-hilding-piankowy-80-200.md
- _products/pl/materace/corato-fdm-piankowy-80-160.md
- _products/pl/materace/dino-spij-zdrowo-kieszeniowy-80-160.md
- _products/pl/materace/dobranocka-hilding-piankowy-60-120.md
- _products/pl/materace/fdm-marina-lateksowy-200-200.md
- _products/pl/materace/fikusny-sen-fiki-miki-piankowy-60-120.md
- _products/pl/materace/hilding-conga-piankowy-200-200.md
- _products/pl/materace/hilding-melody-lateksowy-120-200.md
- _products/pl/materace/hilding-salsa-piankowy-200-200.md
- _products/pl/materace/hilding-step-kieszeniowy-80-200.md
- _products/pl/materace/junior-hevea-lateksowy-80-160.md
- _products/pl/materace/junior-hevea-lateksowy-80-200.md
- _products/pl/materace/kolo-texel-sprezynowy-140x200.md
- _products/pl/materace/kolysanka-hilding-piankowy-60-120.md
- _products/pl/materace/materasso-termopur-comfort-piankowy-120-200.md
- _products/pl/materace/materasso-viscogreen-lux-piankowy-200-200.md
- _products/pl/materace/optimum-syriusz-ps-piankowy-sprezynowy-120-200.md
- _products/pl/materace/safety-smyk-hilding-piankowy-60-120.md
- _products/pl/materace/sembella-cupido-piankowy-120-200.md
- _products/pl/materace/sembella-samba-sprezynowy-200-200.md
- _products/pl/materace/snudo-hevea-piankowy-80-160.md
- _products/pl/materace/snudo-max-hevea-piankowy-80-160.md
- _products/pl/materace/wenus-janpol-kieszeniowy-80-200.md
