---
label: Product [Patelnie]
hide_body: true
fields:
- name: category
  type: text
  config:
    required: false
  label: Kategoria
  hidden: true
  default: patelnie
- name: basics
  type: include
  config: {}
  template: product
  label: Basics
  description: Podstawowe informacje o produkcie
- name: properties
  type: field_group
  config: {}
  fields:
  - name: type
    type: text
    config:
      required: false
    label: Typ
  - name: material
    type: text
    config:
      required: false
    label: Materiał
  - name: brand
    type: text
    config:
      required: false
    label: Marka
  - name: size
    type: text
    config:
      required: false
    label: Rozmiar
  - name: shape
    type: text
    config:
      required: false
    label: Kształt
  - name: coating
    type: text
    config:
      required: false
    label: Powłoka
  - name: lid
    type: text
    config:
      required: false
    label: Pokrywka
  - name: holder
    type: text
    config:
      required: false
    label: Rączka
  - name: color
    type: text
    config:
      required: false
    label: Kolor
  label: Właściwości
  description: Właściwości produktu
pages:
- _products/pl/patelnie/ambition-do-nalesnikow-28-cm-nature-34.md
- _products/pl/patelnie/ambition-nalesnikowa-25-cm-magnat-34152.md
- _products/pl/patelnie/ambition-silverstone-patelnia-grillowa-26x26-20134.md
- _products/pl/patelnie/ambition-silverstone-patelnia-nalesnikowa-26-20135.md
- _products/pl/patelnie/ambition-taurus-patelnia-grillowa-26-cm-34157.md
- _products/pl/patelnie/gerlach-patelnia-28-cm-ceramiczna-harmony-polysk-classic-ilag.md
- _products/pl/patelnie/gerlach-patelnia-ceramiczna-harmony-black-24-cm.md
- _products/pl/patelnie/gerlach-patelnia-granitex-28-cm.md
- _products/pl/patelnie/gerlach-patelnia-grillowa-ceramiczna-natur-24-cm-czarna-32024g.md
- _products/pl/patelnie/kinghoff-patelnia-zeliwna-28-cm-kh1119.md
- _products/pl/patelnie/kitchen-craft-patelnia-zeliwna-z-deska-do-serwowania-artfry-20.md
- _products/pl/patelnie/lamart-patelnia-zeliwna-iron-235-cm-42001828.md
- _products/pl/patelnie/lodge-gleboka-patelnia-zeliwna-30-cm-l10dsk3.md
- _products/pl/patelnie/promis-patelnia-ceramiczna-grillowa-28-cm-ekoceram.md
- _products/pl/patelnie/skeppshult-patelnia-do-smazenia-gleboka-20-cm-0002t.md
- _products/pl/patelnie/tefal-chef-25-cm-c6943802.md
- _products/pl/patelnie/tefal-everest-c6360602-28-cm.md
- _products/pl/patelnie/tefal-talent-pro-25-cm-c6213852.md
- _products/pl/patelnie/zwieger-zwgr-patelnia-28-cm-obsidian-77478.md
- _products/pl/tefal-patelnia-duetto-28-cm-a7040684.md
