---
label: Product [Pozostałe]
hide_body: true
fields:
- name: basics
  type: include
  config: {}
  template: product
  label: Basics
- name: properties
  type: field_group
  config: {}
  fields:
  - name: type
    type: text
    config:
      required: false
    label: Typ
  - name: color
    type: text
    config:
      required: false
    label: Kolor
  label: Właściwości
  description: Użyj ", " aby dodać kilka wartości dla jednej właściwości
