---
label: Product [Pralki]
hide_body: true
fields:
- name: category
  type: text
  config:
    required: false
  label: Kategoria
  hidden: true
  default: pralki
- name: basics
  type: include
  config: {}
  template: product
  label: Basics
  description: Podstawowe informacje o produkcie
- name: properties
  type: field_group
  config: {}
  fields:
  - name: type
    type: text
    config:
      required: false
    label: Typ
    description: Typ pralki
  - name: size
    type: text
    config:
      required: false
    label: Rozmiar
  - name: brand
    type: text
    config:
      required: false
    label: Marka
  - name: energy_class
    type: text
    config:
      required: false
    label: Klasa energetyczna
  - name: type_of_drum
    type: text
    config:
      required: false
    label: Rodzaj bębna
  - name: load
    type: text
    config:
      required: false
    label: Maksymalny załadunek (kg)
  - name: maximum_spin_speed
    type: text
    config:
      required: false
    label: Maksymalna prędkość wirowania
  - name: annual_energy_usage
    type: text
    config:
      required: false
    label: Roczne zużycie energii
  - name: annual_water_usage
    type: text
    config:
      required: false
    label: Roczne zużycie wody
  label: Właściwości
  description: Właściwości produktu
pages:
- _products/pl/pralki/beko-wre5511bww-automatyczna-standard.md
- _products/pl/pralki/bosch-serie-8-waw24740pl-automatyczna-standard.md
- _products/pl/pralki/bosch-wor20155pl-ladowana-od-gory-slim.md
- _products/pl/pralki/candy-cst-360l-ladowana-od-gory-slim.md
- _products/pl/pralki/electrolux-ew6s526wp-perfect-care-automatyczna-slim.md
- _products/pl/pralki/indesit-iwsd-51051-c-eco-pl-automatyczna-standard.md
- _products/pl/pralki/lg-f2j5wn3w-automatyczna-slim.md
- _products/pl/pralki/samsung-eco-bubble-ww70j5346mw-automatyczna-standard.md
- _products/pl/pralki/samsung-ww60k42138w-addwash-automatyczna-slim.md
- _products/pl/pralki/samsung-ww80k5410uw-addwash-automatyczna-standard.md
- _products/pl/pralki/whirlpool-awe4519p-ladowana-od-gory-slim.md
