---
label: Product [Ekspresy do kawy]
hide_body: true
fields:
- name: basics
  type: include
  config: {}
  template: product
  label: Basics
  description: Podstawowe informacje o produkcie
- name: properties
  type: field_group
  config: {}
  fields:
  - name: type
    type: text
    config:
      required: false
    label: Typ
  - name: functionality
    type: text
    config:
      required: false
    label: Funkcjonalność
  - name: brand
    type: text
    config:
      required: false
    label: Marka
  - name: mill
    type: boolean
    label: Posiada młynek
  - name: pressure
    type: text
    config:
      required: false
    label: Ciśnienie
  - name: strength
    type: text
    config:
      required: false
    label: Moc
  - name: type_of_coffee
    type: text
    config:
      required: false
    label: Rodzaj kawy
  - name: milk_frothing_function
    type: boolean
    label: Funkcja spieniania mleka
  - name: mumber_of_types_of_drinks
    type: text
    config:
      required: false
    label: Ilość rodzajów napojów
  - name: warranty
    type: text
    config:
      required: false
    label: Gwarancja
  label: Właściwości
  description: Użyj ", " aby dodać kilka wartości dla jednej właściwości
