---
label: Product [Pralki]
hide_body: true
fields:
- name: basics
  type: include
  config: {}
  template: product
  label: Basics
  description: Podstawowe informacje o produkcie
- name: properties
  type: field_group
  config: {}
  fields:
  - name: type
    type: text
    config:
      required: false
    label: Typ
    description: Typ pralki
  - name: product_size
    type: text
    config:
      required: false
    label: Rozmiar
  - name: brand
    type: text
    config:
      required: false
    label: Marka
  - name: energy_class
    type: text
    config:
      required: false
    label: Klasa energetyczna
  - name: type_of_drum
    type: text
    config:
      required: false
    label: Rodzaj bębna
  - name: load
    type: text
    config:
      required: false
    label: Maksymalny załadunek (kg)
  - name: maximum_spin_speed
    type: text
    config:
      required: false
    label: Maksymalna prędkość wirowania
  - name: annual_energy_usage
    type: text
    config:
      required: false
    label: Roczne zużycie energii
  - name: annual_water_usage
    type: text
    config:
      required: false
    label: Roczne zużycie wody
  label: Właściwości
  description: Użyj ", " aby dodać kilka wartości dla jednej właściwości
pages:
- _products/pl/pralki/bosch-wor20155pl-ladowana-od-gory-slim.md
