---
label: Product [Mattress]
hide_body: true
fields:
- name: basics
  type: include
  config: {}
  template: product
  label: Basics
  description: Podstawowe dane o produkcie
- name: properties
  type: field_group
  config: {}
  fields:
  - name: type
    type: text
    config:
      required: true
    label: Typ
    description: Typ materaca
  - name: size
    type: text
    config:
      required: true
    label: Rozmiar
  - name: brand
    type: text
    config:
      required: true
    label: Marka
  - name: hardness
    type: text
    config:
      required: true
    label: Twardość
  - name: height
    type: text
    config:
      required: true
    label: Wysokość
  - name: inset
    type: text
    config:
      required: true
    label: Wkład
  - name: case
    type: text
    config:
      required: true
    label: Pokrowiec
  - name: bilateral
    type: boolean
    label: Dwustronny
  - name: handles
    type: boolean
    label: Uchwyty
  label: Właściwości
  description: Właściwości produktu
pages:
- collections/_products/pl/mattresses/demeter-janpol-lateksowy-90x200.md
- collections/_products/pl/mattresses/hilding-flamenco-sprezynowy-160x200.md
- collections/_products/pl/mattresses/hilding-rock-roll-piankowy-160x200.md
- collections/_products/pl/mattresses/hilding-salsa-piankowy-160x200.md
- collections/_products/pl/mattresses/ikea-malvik-piankowy-140x200.md
- collections/_products/pl/mattresses/ikea-morgedal-piankowy-160x200.md
- collections/_products/pl/mattresses/janpol-cora-sprezynowy-90x200.md
- collections/_products/pl/mattresses/janpol-wenus-sprezynowy-180x200.md
- collections/_products/pl/mattresses/jysk-gold-f95-dreamzone-piankowy-80x200.md
