---
label: Product [Pralki]
hide_body: true
fields:
- name: category
  type: text
  config:
    required: false
  label: Kategoria
  hidden: true
  default: pralki
- name: basics
  type: include
  config: {}
  template: product
  label: Basics
  description: Podstawowe informacje o produkcie
- name: wlasciwosci
  type: field_group
  config: {}
  label: Właściwości
